credentials: &credentials
  account: {{ cookiecutter.snowflake_account }}
  user: {{ cookiecutter.user_email }}

dev_schema: &dev-schema
  schema: dev_{{ cookiecutter.user_initials }}

# Only change below this line if you know what you're doing
# =========================================================

{{ cookiecutter._project_slug_safe }}:
  target: dev
  outputs:
    dev:
      type: snowflake 
      # More information for the options in this file
      # can be found here: https://docs.getdbt.com/dbt-cli/configure-your-profile
      <<: *credentials 
      <<: *dev-schema

      authenticator: externalbrowser 
      role: {{ cookiecutter._project_prefix_safe }}_TRANSFORMER 
      warehouse: {{ cookiecutter._project_prefix_safe }}_TRANSFORMER_WH
      database: {{ cookiecutter._project_prefix_safe }}_DEV
      threads: 8

    prod:
      type: snowflake 
      <<: *credentials

      authenticator: externalbrowser 
      role: {{ cookiecutter._project_prefix_safe }}_DEPLOYER 
      warehouse: {{ cookiecutter._project_prefix_safe }}_DEPLOYER_WH
      database: {{ cookiecutter._project_prefix_safe }}
      schema: {{ cookiecutter._project_analysis_schema_safe }}
      threads: 8

    admin:
      type: snowflake 
      <<: *credentials 

      account: {{ cookiecutter.snowflake_account }}
      authenticator: externalbrowser 
      role: {{ cookiecutter._project_prefix_safe }}_ADMIN 
      warehouse: {{ cookiecutter._project_prefix_safe }}_ADMIN_WH
      database: {{ cookiecutter._project_prefix_safe }}
      schema: {{ cookiecutter._project_analysis_schema_safe }}
      threads: 8

    super-admin:
      type: snowflake 
      <<: *credentials

      authenticator: externalbrowser 
      role: ACCOUNTADMIN
      warehouse: ADMIN_WH
      database: {{ cookiecutter._project_prefix_safe }}
      schema: {{ cookiecutter._project_analysis_schema_safe }}
      threads: 8